# Generated by Django 3.1.5 on 2021-01-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_books_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
